// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cardboard_device.proto

package com.alphacircle;

import com.google.protobuf.GeneratedMessageLite;

public final class CardboardDevice {
  private CardboardDevice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DeviceParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cardboard.DeviceParams)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * String identifying the device's vendor (e.g. "Google, Inc.").
     * A device's [vendor, model] pair is expected to be globally unique.
     * </pre>
     *
     * <code>optional string vendor = 1;</code>
     */
    boolean hasVendor();
    /**
     * <pre>
     * String identifying the device's vendor (e.g. "Google, Inc.").
     * A device's [vendor, model] pair is expected to be globally unique.
     * </pre>
     *
     * <code>optional string vendor = 1;</code>
     */
    java.lang.String getVendor();
    /**
     * <pre>
     * String identifying the device's vendor (e.g. "Google, Inc.").
     * A device's [vendor, model] pair is expected to be globally unique.
     * </pre>
     *
     * <code>optional string vendor = 1;</code>
     */
    com.google.protobuf.ByteString
        getVendorBytes();

    /**
     * <pre>
     * String identifying the device's model, including revision info if
     * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
     * expected to be globally unique.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     */
    boolean hasModel();
    /**
     * <pre>
     * String identifying the device's model, including revision info if
     * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
     * expected to be globally unique.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     */
    java.lang.String getModel();
    /**
     * <pre>
     * String identifying the device's model, including revision info if
     * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
     * expected to be globally unique.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <pre>
     * Distance from the display screen to the optical center of lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float screen_to_lens_distance = 3;</code>
     */
    boolean hasScreenToLensDistance();
    /**
     * <pre>
     * Distance from the display screen to the optical center of lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float screen_to_lens_distance = 3;</code>
     */
    float getScreenToLensDistance();

    /**
     * <pre>
     * Horizontal distance between optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float inter_lens_distance = 4;</code>
     */
    boolean hasInterLensDistance();
    /**
     * <pre>
     * Horizontal distance between optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float inter_lens_distance = 4;</code>
     */
    float getInterLensDistance();

    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    java.util.List<java.lang.Float> getLeftEyeFieldOfViewAnglesList();
    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    int getLeftEyeFieldOfViewAnglesCount();
    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    float getLeftEyeFieldOfViewAngles(int index);

    /**
     * <pre>
     * Set according to vertical alignment strategy-- see enum comments above.
     * NOTE: If you set this to CENTER, see special instructions for the
     * tray_to_lens_distance field below.
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
     */
    boolean hasVerticalAlignment();
    /**
     * <pre>
     * Set according to vertical alignment strategy-- see enum comments above.
     * NOTE: If you set this to CENTER, see special instructions for the
     * tray_to_lens_distance field below.
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
     */
    DeviceParams.VerticalAlignmentType getVerticalAlignment();

    /**
     * <pre>
     * If the phone is aligned vertically within the device by resting against
     * a fixed top or bottom tray, this is the distance from the tray to
     * optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * NOTE: Due to a bug in initial versions of the SDK's, this field
     * must be set explicitly to .035 when vertical_alignment = CENTER.
     * </pre>
     *
     * <code>optional float tray_to_lens_distance = 6;</code>
     */
    boolean hasTrayToLensDistance();
    /**
     * <pre>
     * If the phone is aligned vertically within the device by resting against
     * a fixed top or bottom tray, this is the distance from the tray to
     * optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * NOTE: Due to a bug in initial versions of the SDK's, this field
     * must be set explicitly to .035 when vertical_alignment = CENTER.
     * </pre>
     *
     * <code>optional float tray_to_lens_distance = 6;</code>
     */
    float getTrayToLensDistance();

    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    java.util.List<java.lang.Float> getDistortionCoefficientsList();
    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    int getDistortionCoefficientsCount();
    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    float getDistortionCoefficients(int index);

    /**
     * <pre>
     * Specify primary input mechanism of the HMD.  Intended for advisory
     * purposes only, to address simple questions such as "can HMD
     * be used with apps requiring a physical button event?" or "what icon
     * should be used to represent button action to the user?".
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
     */
    boolean hasPrimaryButton();
    /**
     * <pre>
     * Specify primary input mechanism of the HMD.  Intended for advisory
     * purposes only, to address simple questions such as "can HMD
     * be used with apps requiring a physical button event?" or "what icon
     * should be used to represent button action to the user?".
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
     */
    DeviceParams.ButtonType getPrimaryButton();
  }
  /**
   * <pre>
   **
   * Message describing properties of a VR head mount device (HMD) which uses an
   * interchangeable smartphone as a display (e.g. Google Cardboard).
   * While some properties are certain (e.g. inter_lens_distance), others
   * represent nominal values which may be refined depending on context (e.g.
   * viewport_angles).
   * Lengths are in meters unless noted otherwise.  Fields are _required_
   * unless noted otherwise.
   * Some context on why this set of parameters are deemed necessary and
   * sufficient:
   *    * FOV scale can be reasonably approximated from lens-to-screen distance
   *      and display size (i.e. knowing lens focal length isn't crucial).
   *    * Lenses are assumed to be horizontally centered with respect to
   *      display.
   *    * The display is not necessarily vertically centered.  For interchangeable
   *      phones where the device rests against a tray, we can derive
   *      the vertical offset from tray-to-lens height along with phone-specific
   *      bezel and screen sizes (supplied separately).
   * </pre>
   *
   * Protobuf type {@code cardboard.DeviceParams}
   */
  public  static final class DeviceParams extends
      com.google.protobuf.GeneratedMessageLite<
          DeviceParams, DeviceParams.Builder> implements
      // @@protoc_insertion_point(message_implements:cardboard.DeviceParams)
      DeviceParamsOrBuilder {
    private DeviceParams() {
      vendor_ = "";
      model_ = "";
      leftEyeFieldOfViewAngles_ = emptyFloatList();
      distortionCoefficients_ = emptyFloatList();
      primaryButton_ = 1;
    }
    /**
     * Protobuf enum {@code cardboard.DeviceParams.VerticalAlignmentType}
     */
    public enum VerticalAlignmentType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <pre>
       * phone rests against a fixed bottom tray
       * </pre>
       *
       * <code>BOTTOM = 0;</code>
       */
      BOTTOM(0),
      /**
       * <pre>
       * phone screen assumed to be centered w.r.t. lenses
       * </pre>
       *
       * <code>CENTER = 1;</code>
       */
      CENTER(1),
      /**
       * <pre>
       * phone rests against a fixed top tray
       * </pre>
       *
       * <code>TOP = 2;</code>
       */
      TOP(2),
      ;

      /**
       * <pre>
       * phone rests against a fixed bottom tray
       * </pre>
       *
       * <code>BOTTOM = 0;</code>
       */
      public static final int BOTTOM_VALUE = 0;
      /**
       * <pre>
       * phone screen assumed to be centered w.r.t. lenses
       * </pre>
       *
       * <code>CENTER = 1;</code>
       */
      public static final int CENTER_VALUE = 1;
      /**
       * <pre>
       * phone rests against a fixed top tray
       * </pre>
       *
       * <code>TOP = 2;</code>
       */
      public static final int TOP_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static VerticalAlignmentType valueOf(int value) {
        return forNumber(value);
      }

      public static VerticalAlignmentType forNumber(int value) {
        switch (value) {
          case 0: return BOTTOM;
          case 1: return CENTER;
          case 2: return TOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<VerticalAlignmentType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          VerticalAlignmentType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<VerticalAlignmentType>() {
              public VerticalAlignmentType findValueByNumber(int number) {
                return VerticalAlignmentType.forNumber(number);
              }
            };

      private final int value;

      private VerticalAlignmentType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cardboard.DeviceParams.VerticalAlignmentType)
    }

    /**
     * Protobuf enum {@code cardboard.DeviceParams.ButtonType}
     */
    public enum ButtonType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <pre>
       * No physical button, and touch screen is not easily accessible.
       * </pre>
       *
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <pre>
       * HMD has integrated magnet switch similar to original Cardboard.
       * </pre>
       *
       * <code>MAGNET = 1;</code>
       */
      MAGNET(1),
      /**
       * <pre>
       * At least a portion of touch screen is easily accessible to user for taps.
       * </pre>
       *
       * <code>TOUCH = 2;</code>
       */
      TOUCH(2),
      /**
       * <pre>
       * Touch screen is triggered indirectly via integrated button on the HMD.
       * </pre>
       *
       * <code>INDIRECT_TOUCH = 3;</code>
       */
      INDIRECT_TOUCH(3),
      ;

      /**
       * <pre>
       * No physical button, and touch screen is not easily accessible.
       * </pre>
       *
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <pre>
       * HMD has integrated magnet switch similar to original Cardboard.
       * </pre>
       *
       * <code>MAGNET = 1;</code>
       */
      public static final int MAGNET_VALUE = 1;
      /**
       * <pre>
       * At least a portion of touch screen is easily accessible to user for taps.
       * </pre>
       *
       * <code>TOUCH = 2;</code>
       */
      public static final int TOUCH_VALUE = 2;
      /**
       * <pre>
       * Touch screen is triggered indirectly via integrated button on the HMD.
       * </pre>
       *
       * <code>INDIRECT_TOUCH = 3;</code>
       */
      public static final int INDIRECT_TOUCH_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ButtonType valueOf(int value) {
        return forNumber(value);
      }

      public static ButtonType forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return MAGNET;
          case 2: return TOUCH;
          case 3: return INDIRECT_TOUCH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ButtonType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ButtonType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ButtonType>() {
              public ButtonType findValueByNumber(int number) {
                return ButtonType.forNumber(number);
              }
            };

      private final int value;

      private ButtonType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cardboard.DeviceParams.ButtonType)
    }

    private int bitField0_;
    public static final int VENDOR_FIELD_NUMBER = 1;
    private java.lang.String vendor_;
    /**
     * <pre>
     * String identifying the device's vendor (e.g. "Google, Inc.").
     * A device's [vendor, model] pair is expected to be globally unique.
     * </pre>
     *
     * <code>optional string vendor = 1;</code>
     */
    public boolean hasVendor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * String identifying the device's vendor (e.g. "Google, Inc.").
     * A device's [vendor, model] pair is expected to be globally unique.
     * </pre>
     *
     * <code>optional string vendor = 1;</code>
     */
    public java.lang.String getVendor() {
      return vendor_;
    }
    /**
     * <pre>
     * String identifying the device's vendor (e.g. "Google, Inc.").
     * A device's [vendor, model] pair is expected to be globally unique.
     * </pre>
     *
     * <code>optional string vendor = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVendorBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(vendor_);
    }
    /**
     * <pre>
     * String identifying the device's vendor (e.g. "Google, Inc.").
     * A device's [vendor, model] pair is expected to be globally unique.
     * </pre>
     *
     * <code>optional string vendor = 1;</code>
     */
    private void setVendor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      vendor_ = value;
    }
    /**
     * <pre>
     * String identifying the device's vendor (e.g. "Google, Inc.").
     * A device's [vendor, model] pair is expected to be globally unique.
     * </pre>
     *
     * <code>optional string vendor = 1;</code>
     */
    private void clearVendor() {
      bitField0_ = (bitField0_ & ~0x00000001);
      vendor_ = getDefaultInstance().getVendor();
    }
    /**
     * <pre>
     * String identifying the device's vendor (e.g. "Google, Inc.").
     * A device's [vendor, model] pair is expected to be globally unique.
     * </pre>
     *
     * <code>optional string vendor = 1;</code>
     */
    private void setVendorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      vendor_ = value.toStringUtf8();
    }

    public static final int MODEL_FIELD_NUMBER = 2;
    private java.lang.String model_;
    /**
     * <pre>
     * String identifying the device's model, including revision info if
     * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
     * expected to be globally unique.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * String identifying the device's model, including revision info if
     * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
     * expected to be globally unique.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     */
    public java.lang.String getModel() {
      return model_;
    }
    /**
     * <pre>
     * String identifying the device's model, including revision info if
     * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
     * expected to be globally unique.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(model_);
    }
    /**
     * <pre>
     * String identifying the device's model, including revision info if
     * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
     * expected to be globally unique.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     */
    private void setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      model_ = value;
    }
    /**
     * <pre>
     * String identifying the device's model, including revision info if
     * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
     * expected to be globally unique.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     */
    private void clearModel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      model_ = getDefaultInstance().getModel();
    }
    /**
     * <pre>
     * String identifying the device's model, including revision info if
     * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
     * expected to be globally unique.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     */
    private void setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      model_ = value.toStringUtf8();
    }

    public static final int SCREEN_TO_LENS_DISTANCE_FIELD_NUMBER = 3;
    private float screenToLensDistance_;
    /**
     * <pre>
     * Distance from the display screen to the optical center of lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float screen_to_lens_distance = 3;</code>
     */
    public boolean hasScreenToLensDistance() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Distance from the display screen to the optical center of lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float screen_to_lens_distance = 3;</code>
     */
    public float getScreenToLensDistance() {
      return screenToLensDistance_;
    }
    /**
     * <pre>
     * Distance from the display screen to the optical center of lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float screen_to_lens_distance = 3;</code>
     */
    private void setScreenToLensDistance(float value) {
      bitField0_ |= 0x00000004;
      screenToLensDistance_ = value;
    }
    /**
     * <pre>
     * Distance from the display screen to the optical center of lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float screen_to_lens_distance = 3;</code>
     */
    private void clearScreenToLensDistance() {
      bitField0_ = (bitField0_ & ~0x00000004);
      screenToLensDistance_ = 0F;
    }

    public static final int INTER_LENS_DISTANCE_FIELD_NUMBER = 4;
    private float interLensDistance_;
    /**
     * <pre>
     * Horizontal distance between optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float inter_lens_distance = 4;</code>
     */
    public boolean hasInterLensDistance() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * Horizontal distance between optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float inter_lens_distance = 4;</code>
     */
    public float getInterLensDistance() {
      return interLensDistance_;
    }
    /**
     * <pre>
     * Horizontal distance between optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float inter_lens_distance = 4;</code>
     */
    private void setInterLensDistance(float value) {
      bitField0_ |= 0x00000008;
      interLensDistance_ = value;
    }
    /**
     * <pre>
     * Horizontal distance between optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * </pre>
     *
     * <code>optional float inter_lens_distance = 4;</code>
     */
    private void clearInterLensDistance() {
      bitField0_ = (bitField0_ & ~0x00000008);
      interLensDistance_ = 0F;
    }

    public static final int LEFT_EYE_FIELD_OF_VIEW_ANGLES_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.FloatList leftEyeFieldOfViewAngles_;
    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    public java.util.List<java.lang.Float>
        getLeftEyeFieldOfViewAnglesList() {
      return leftEyeFieldOfViewAngles_;
    }
    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    public int getLeftEyeFieldOfViewAnglesCount() {
      return leftEyeFieldOfViewAngles_.size();
    }
    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    public float getLeftEyeFieldOfViewAngles(int index) {
      return leftEyeFieldOfViewAngles_.getFloat(index);
    }
    private int leftEyeFieldOfViewAnglesMemoizedSerializedSize = -1;
    private void ensureLeftEyeFieldOfViewAnglesIsMutable() {
      if (!leftEyeFieldOfViewAngles_.isModifiable()) {
        leftEyeFieldOfViewAngles_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(leftEyeFieldOfViewAngles_);
       }
    }
    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    private void setLeftEyeFieldOfViewAngles(
        int index, float value) {
      ensureLeftEyeFieldOfViewAnglesIsMutable();
      leftEyeFieldOfViewAngles_.setFloat(index, value);
    }
    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    private void addLeftEyeFieldOfViewAngles(float value) {
      ensureLeftEyeFieldOfViewAnglesIsMutable();
      leftEyeFieldOfViewAngles_.addFloat(value);
    }
    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    private void addAllLeftEyeFieldOfViewAngles(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureLeftEyeFieldOfViewAnglesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, leftEyeFieldOfViewAngles_);
    }
    /**
     * <pre>
     * Four-element tuple (left, right, bottom, top) of left eye's view extent
     * angles relative to center, assuming the following:
     *     * eye is aligned with optical center of lens
     *     * display screen is equal or larger than extents viewable through lens
     *     * nominal eye-to-lens distance
     *     * mirrored field of view will be applied to the right eye
     * These values are essentially used as an optimization to avoid rendering
     * pixels which can't be seen.
     * This is a required field for distortion rendering, and angles must be
     * positive.
     * </pre>
     *
     * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
     */
    private void clearLeftEyeFieldOfViewAngles() {
      leftEyeFieldOfViewAngles_ = emptyFloatList();
    }

    public static final int VERTICAL_ALIGNMENT_FIELD_NUMBER = 11;
    private int verticalAlignment_;
    /**
     * <pre>
     * Set according to vertical alignment strategy-- see enum comments above.
     * NOTE: If you set this to CENTER, see special instructions for the
     * tray_to_lens_distance field below.
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
     */
    public boolean hasVerticalAlignment() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * Set according to vertical alignment strategy-- see enum comments above.
     * NOTE: If you set this to CENTER, see special instructions for the
     * tray_to_lens_distance field below.
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
     * @return
     */
    public CardboardDevice.DeviceParams.VerticalAlignmentType getVerticalAlignment() {
      DeviceParams.VerticalAlignmentType result = DeviceParams.VerticalAlignmentType.forNumber(verticalAlignment_);
      return result == null ? CardboardDevice.DeviceParams.VerticalAlignmentType.BOTTOM : result;
    }
    /**
     * <pre>
     * Set according to vertical alignment strategy-- see enum comments above.
     * NOTE: If you set this to CENTER, see special instructions for the
     * tray_to_lens_distance field below.
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
     */
    private void setVerticalAlignment(CardboardDevice.DeviceParams.VerticalAlignmentType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      verticalAlignment_ = value.getNumber();
    }
    /**
     * <pre>
     * Set according to vertical alignment strategy-- see enum comments above.
     * NOTE: If you set this to CENTER, see special instructions for the
     * tray_to_lens_distance field below.
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
     */
    private void clearVerticalAlignment() {
      bitField0_ = (bitField0_ & ~0x00000010);
      verticalAlignment_ = 0;
    }

    public static final int TRAY_TO_LENS_DISTANCE_FIELD_NUMBER = 6;
    private float trayToLensDistance_;
    /**
     * <pre>
     * If the phone is aligned vertically within the device by resting against
     * a fixed top or bottom tray, this is the distance from the tray to
     * optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * NOTE: Due to a bug in initial versions of the SDK's, this field
     * must be set explicitly to .035 when vertical_alignment = CENTER.
     * </pre>
     *
     * <code>optional float tray_to_lens_distance = 6;</code>
     */
    public boolean hasTrayToLensDistance() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * If the phone is aligned vertically within the device by resting against
     * a fixed top or bottom tray, this is the distance from the tray to
     * optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * NOTE: Due to a bug in initial versions of the SDK's, this field
     * must be set explicitly to .035 when vertical_alignment = CENTER.
     * </pre>
     *
     * <code>optional float tray_to_lens_distance = 6;</code>
     */
    public float getTrayToLensDistance() {
      return trayToLensDistance_;
    }
    /**
     * <pre>
     * If the phone is aligned vertically within the device by resting against
     * a fixed top or bottom tray, this is the distance from the tray to
     * optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * NOTE: Due to a bug in initial versions of the SDK's, this field
     * must be set explicitly to .035 when vertical_alignment = CENTER.
     * </pre>
     *
     * <code>optional float tray_to_lens_distance = 6;</code>
     */
    private void setTrayToLensDistance(float value) {
      bitField0_ |= 0x00000020;
      trayToLensDistance_ = value;
    }
    /**
     * <pre>
     * If the phone is aligned vertically within the device by resting against
     * a fixed top or bottom tray, this is the distance from the tray to
     * optical center of the lenses.
     * This is a required field for distortion rendering, and must be positive.
     * NOTE: Due to a bug in initial versions of the SDK's, this field
     * must be set explicitly to .035 when vertical_alignment = CENTER.
     * </pre>
     *
     * <code>optional float tray_to_lens_distance = 6;</code>
     */
    private void clearTrayToLensDistance() {
      bitField0_ = (bitField0_ & ~0x00000020);
      trayToLensDistance_ = 0F;
    }

    public static final int DISTORTION_COEFFICIENTS_FIELD_NUMBER = 7;
    private com.google.protobuf.Internal.FloatList distortionCoefficients_;
    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    public java.util.List<java.lang.Float>
        getDistortionCoefficientsList() {
      return distortionCoefficients_;
    }
    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    public int getDistortionCoefficientsCount() {
      return distortionCoefficients_.size();
    }
    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    public float getDistortionCoefficients(int index) {
      return distortionCoefficients_.getFloat(index);
    }
    private int distortionCoefficientsMemoizedSerializedSize = -1;
    private void ensureDistortionCoefficientsIsMutable() {
      if (!distortionCoefficients_.isModifiable()) {
        distortionCoefficients_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(distortionCoefficients_);
       }
    }
    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    private void setDistortionCoefficients(
        int index, float value) {
      ensureDistortionCoefficientsIsMutable();
      distortionCoefficients_.setFloat(index, value);
    }
    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    private void addDistortionCoefficients(float value) {
      ensureDistortionCoefficientsIsMutable();
      distortionCoefficients_.addFloat(value);
    }
    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    private void addAllDistortionCoefficients(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureDistortionCoefficientsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, distortionCoefficients_);
    }
    /**
     * <pre>
     * Coefficients Ki for pincushion distortion function which maps
     * from position on real screen to virtual screen (i.e. texture) relative
     * to optical center:
     *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
     * where r is the distance in tan-angle units from the optical center,
     * p the input point, and p' the output point.  Tan-angle units can be
     * computed as distance on the screen divided by distance from the
     * virtual eye to the screen.
     * </pre>
     *
     * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
     */
    private void clearDistortionCoefficients() {
      distortionCoefficients_ = emptyFloatList();
    }

    public static final int PRIMARY_BUTTON_FIELD_NUMBER = 12;
    private int primaryButton_;
    /**
     * <pre>
     * Specify primary input mechanism of the HMD.  Intended for advisory
     * purposes only, to address simple questions such as "can HMD
     * be used with apps requiring a physical button event?" or "what icon
     * should be used to represent button action to the user?".
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
     */
    public boolean hasPrimaryButton() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * Specify primary input mechanism of the HMD.  Intended for advisory
     * purposes only, to address simple questions such as "can HMD
     * be used with apps requiring a physical button event?" or "what icon
     * should be used to represent button action to the user?".
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
     */
    public DeviceParams.ButtonType getPrimaryButton() {
      DeviceParams.ButtonType result = DeviceParams.ButtonType.forNumber(primaryButton_);
      return result == null ? DeviceParams.ButtonType.MAGNET : result;
    }
    /**
     * <pre>
     * Specify primary input mechanism of the HMD.  Intended for advisory
     * purposes only, to address simple questions such as "can HMD
     * be used with apps requiring a physical button event?" or "what icon
     * should be used to represent button action to the user?".
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
     */
    private void setPrimaryButton(DeviceParams.ButtonType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      primaryButton_ = value.getNumber();
    }
    /**
     * <pre>
     * Specify primary input mechanism of the HMD.  Intended for advisory
     * purposes only, to address simple questions such as "can HMD
     * be used with apps requiring a physical button event?" or "what icon
     * should be used to represent button action to the user?".
     * </pre>
     *
     * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
     */
    private void clearPrimaryButton() {
      bitField0_ = (bitField0_ & ~0x00000040);
      primaryButton_ = 1;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getVendor());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getModel());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, screenToLensDistance_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, interLensDistance_);
      }
      if (getLeftEyeFieldOfViewAnglesList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(leftEyeFieldOfViewAnglesMemoizedSerializedSize);
      }
      for (int i = 0; i < leftEyeFieldOfViewAngles_.size(); i++) {
        output.writeFloatNoTag(leftEyeFieldOfViewAngles_.getFloat(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, trayToLensDistance_);
      }
      if (getDistortionCoefficientsList().size() > 0) {
        output.writeUInt32NoTag(58);
        output.writeUInt32NoTag(distortionCoefficientsMemoizedSerializedSize);
      }
      for (int i = 0; i < distortionCoefficients_.size(); i++) {
        output.writeFloatNoTag(distortionCoefficients_.getFloat(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(11, verticalAlignment_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(12, primaryButton_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getVendor());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getModel());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, screenToLensDistance_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, interLensDistance_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getLeftEyeFieldOfViewAnglesList().size();
        size += dataSize;
        if (!getLeftEyeFieldOfViewAnglesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        leftEyeFieldOfViewAnglesMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, trayToLensDistance_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getDistortionCoefficientsList().size();
        size += dataSize;
        if (!getDistortionCoefficientsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        distortionCoefficientsMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, verticalAlignment_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(12, primaryButton_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static DeviceParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static DeviceParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static DeviceParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static DeviceParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static DeviceParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CardboardDevice.DeviceParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static DeviceParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static CardboardDevice.DeviceParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CardboardDevice.DeviceParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CardboardDevice.DeviceParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DeviceParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     **
     * Message describing properties of a VR head mount device (HMD) which uses an
     * interchangeable smartphone as a display (e.g. Google Cardboard).
     * While some properties are certain (e.g. inter_lens_distance), others
     * represent nominal values which may be refined depending on context (e.g.
     * viewport_angles).
     * Lengths are in meters unless noted otherwise.  Fields are _required_
     * unless noted otherwise.
     * Some context on why this set of parameters are deemed necessary and
     * sufficient:
     *    * FOV scale can be reasonably approximated from lens-to-screen distance
     *      and display size (i.e. knowing lens focal length isn't crucial).
     *    * Lenses are assumed to be horizontally centered with respect to
     *      display.
     *    * The display is not necessarily vertically centered.  For interchangeable
     *      phones where the device rests against a tray, we can derive
     *      the vertical offset from tray-to-lens height along with phone-specific
     *      bezel and screen sizes (supplied separately).
     * </pre>
     *
     * Protobuf type {@code cardboard.DeviceParams}
     */
    public static final class Builder extends
        GeneratedMessageLite.Builder<
          CardboardDevice.DeviceParams, Builder> implements
        // @@protoc_insertion_point(builder_implements:cardboard.DeviceParams)
        CardboardDevice.DeviceParamsOrBuilder {
      // Construct using com.google.cardboard.proto.CardboardDevice.DeviceParams.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * String identifying the device's vendor (e.g. "Google, Inc.").
       * A device's [vendor, model] pair is expected to be globally unique.
       * </pre>
       *
       * <code>optional string vendor = 1;</code>
       */
      public boolean hasVendor() {
        return instance.hasVendor();
      }
      /**
       * <pre>
       * String identifying the device's vendor (e.g. "Google, Inc.").
       * A device's [vendor, model] pair is expected to be globally unique.
       * </pre>
       *
       * <code>optional string vendor = 1;</code>
       */
      public java.lang.String getVendor() {
        return instance.getVendor();
      }
      /**
       * <pre>
       * String identifying the device's vendor (e.g. "Google, Inc.").
       * A device's [vendor, model] pair is expected to be globally unique.
       * </pre>
       *
       * <code>optional string vendor = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVendorBytes() {
        return instance.getVendorBytes();
      }
      /**
       * <pre>
       * String identifying the device's vendor (e.g. "Google, Inc.").
       * A device's [vendor, model] pair is expected to be globally unique.
       * </pre>
       *
       * <code>optional string vendor = 1;</code>
       */
      public Builder setVendor(
          java.lang.String value) {
        copyOnWrite();
        instance.setVendor(value);
        return this;
      }
      /**
       * <pre>
       * String identifying the device's vendor (e.g. "Google, Inc.").
       * A device's [vendor, model] pair is expected to be globally unique.
       * </pre>
       *
       * <code>optional string vendor = 1;</code>
       */
      public Builder clearVendor() {
        copyOnWrite();
        instance.clearVendor();
        return this;
      }
      /**
       * <pre>
       * String identifying the device's vendor (e.g. "Google, Inc.").
       * A device's [vendor, model] pair is expected to be globally unique.
       * </pre>
       *
       * <code>optional string vendor = 1;</code>
       */
      public Builder setVendorBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVendorBytes(value);
        return this;
      }

      /**
       * <pre>
       * String identifying the device's model, including revision info if
       * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
       * expected to be globally unique.
       * </pre>
       *
       * <code>optional string model = 2;</code>
       */
      public boolean hasModel() {
        return instance.hasModel();
      }
      /**
       * <pre>
       * String identifying the device's model, including revision info if
       * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
       * expected to be globally unique.
       * </pre>
       *
       * <code>optional string model = 2;</code>
       */
      public java.lang.String getModel() {
        return instance.getModel();
      }
      /**
       * <pre>
       * String identifying the device's model, including revision info if
       * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
       * expected to be globally unique.
       * </pre>
       *
       * <code>optional string model = 2;</code>
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        return instance.getModelBytes();
      }
      /**
       * <pre>
       * String identifying the device's model, including revision info if
       * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
       * expected to be globally unique.
       * </pre>
       *
       * <code>optional string model = 2;</code>
       */
      public Builder setModel(
          java.lang.String value) {
        copyOnWrite();
        instance.setModel(value);
        return this;
      }
      /**
       * <pre>
       * String identifying the device's model, including revision info if
       * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
       * expected to be globally unique.
       * </pre>
       *
       * <code>optional string model = 2;</code>
       */
      public Builder clearModel() {
        copyOnWrite();
        instance.clearModel();
        return this;
      }
      /**
       * <pre>
       * String identifying the device's model, including revision info if
       * needed (e.g. "Cardboard v1").  A device's [vendor, model] pair is
       * expected to be globally unique.
       * </pre>
       *
       * <code>optional string model = 2;</code>
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setModelBytes(value);
        return this;
      }

      /**
       * <pre>
       * Distance from the display screen to the optical center of lenses.
       * This is a required field for distortion rendering, and must be positive.
       * </pre>
       *
       * <code>optional float screen_to_lens_distance = 3;</code>
       */
      public boolean hasScreenToLensDistance() {
        return instance.hasScreenToLensDistance();
      }
      /**
       * <pre>
       * Distance from the display screen to the optical center of lenses.
       * This is a required field for distortion rendering, and must be positive.
       * </pre>
       *
       * <code>optional float screen_to_lens_distance = 3;</code>
       */
      public float getScreenToLensDistance() {
        return instance.getScreenToLensDistance();
      }
      /**
       * <pre>
       * Distance from the display screen to the optical center of lenses.
       * This is a required field for distortion rendering, and must be positive.
       * </pre>
       *
       * <code>optional float screen_to_lens_distance = 3;</code>
       */
      public Builder setScreenToLensDistance(float value) {
        copyOnWrite();
        instance.setScreenToLensDistance(value);
        return this;
      }
      /**
       * <pre>
       * Distance from the display screen to the optical center of lenses.
       * This is a required field for distortion rendering, and must be positive.
       * </pre>
       *
       * <code>optional float screen_to_lens_distance = 3;</code>
       */
      public Builder clearScreenToLensDistance() {
        copyOnWrite();
        instance.clearScreenToLensDistance();
        return this;
      }

      /**
       * <pre>
       * Horizontal distance between optical center of the lenses.
       * This is a required field for distortion rendering, and must be positive.
       * </pre>
       *
       * <code>optional float inter_lens_distance = 4;</code>
       */
      public boolean hasInterLensDistance() {
        return instance.hasInterLensDistance();
      }
      /**
       * <pre>
       * Horizontal distance between optical center of the lenses.
       * This is a required field for distortion rendering, and must be positive.
       * </pre>
       *
       * <code>optional float inter_lens_distance = 4;</code>
       */
      public float getInterLensDistance() {
        return instance.getInterLensDistance();
      }
      /**
       * <pre>
       * Horizontal distance between optical center of the lenses.
       * This is a required field for distortion rendering, and must be positive.
       * </pre>
       *
       * <code>optional float inter_lens_distance = 4;</code>
       */
      public Builder setInterLensDistance(float value) {
        copyOnWrite();
        instance.setInterLensDistance(value);
        return this;
      }
      /**
       * <pre>
       * Horizontal distance between optical center of the lenses.
       * This is a required field for distortion rendering, and must be positive.
       * </pre>
       *
       * <code>optional float inter_lens_distance = 4;</code>
       */
      public Builder clearInterLensDistance() {
        copyOnWrite();
        instance.clearInterLensDistance();
        return this;
      }

      /**
       * <pre>
       * Four-element tuple (left, right, bottom, top) of left eye's view extent
       * angles relative to center, assuming the following:
       *     * eye is aligned with optical center of lens
       *     * display screen is equal or larger than extents viewable through lens
       *     * nominal eye-to-lens distance
       *     * mirrored field of view will be applied to the right eye
       * These values are essentially used as an optimization to avoid rendering
       * pixels which can't be seen.
       * This is a required field for distortion rendering, and angles must be
       * positive.
       * </pre>
       *
       * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
       */
      public java.util.List<java.lang.Float>
          getLeftEyeFieldOfViewAnglesList() {
        return java.util.Collections.unmodifiableList(
            instance.getLeftEyeFieldOfViewAnglesList());
      }
      /**
       * <pre>
       * Four-element tuple (left, right, bottom, top) of left eye's view extent
       * angles relative to center, assuming the following:
       *     * eye is aligned with optical center of lens
       *     * display screen is equal or larger than extents viewable through lens
       *     * nominal eye-to-lens distance
       *     * mirrored field of view will be applied to the right eye
       * These values are essentially used as an optimization to avoid rendering
       * pixels which can't be seen.
       * This is a required field for distortion rendering, and angles must be
       * positive.
       * </pre>
       *
       * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
       */
      public int getLeftEyeFieldOfViewAnglesCount() {
        return instance.getLeftEyeFieldOfViewAnglesCount();
      }
      /**
       * <pre>
       * Four-element tuple (left, right, bottom, top) of left eye's view extent
       * angles relative to center, assuming the following:
       *     * eye is aligned with optical center of lens
       *     * display screen is equal or larger than extents viewable through lens
       *     * nominal eye-to-lens distance
       *     * mirrored field of view will be applied to the right eye
       * These values are essentially used as an optimization to avoid rendering
       * pixels which can't be seen.
       * This is a required field for distortion rendering, and angles must be
       * positive.
       * </pre>
       *
       * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
       */
      public float getLeftEyeFieldOfViewAngles(int index) {
        return instance.getLeftEyeFieldOfViewAngles(index);
      }
      /**
       * <pre>
       * Four-element tuple (left, right, bottom, top) of left eye's view extent
       * angles relative to center, assuming the following:
       *     * eye is aligned with optical center of lens
       *     * display screen is equal or larger than extents viewable through lens
       *     * nominal eye-to-lens distance
       *     * mirrored field of view will be applied to the right eye
       * These values are essentially used as an optimization to avoid rendering
       * pixels which can't be seen.
       * This is a required field for distortion rendering, and angles must be
       * positive.
       * </pre>
       *
       * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
       */
      public Builder setLeftEyeFieldOfViewAngles(
          int index, float value) {
        copyOnWrite();
        instance.setLeftEyeFieldOfViewAngles(index, value);
        return this;
      }
      /**
       * <pre>
       * Four-element tuple (left, right, bottom, top) of left eye's view extent
       * angles relative to center, assuming the following:
       *     * eye is aligned with optical center of lens
       *     * display screen is equal or larger than extents viewable through lens
       *     * nominal eye-to-lens distance
       *     * mirrored field of view will be applied to the right eye
       * These values are essentially used as an optimization to avoid rendering
       * pixels which can't be seen.
       * This is a required field for distortion rendering, and angles must be
       * positive.
       * </pre>
       *
       * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
       */
      public Builder addLeftEyeFieldOfViewAngles(float value) {
        copyOnWrite();
        instance.addLeftEyeFieldOfViewAngles(value);
        return this;
      }
      /**
       * <pre>
       * Four-element tuple (left, right, bottom, top) of left eye's view extent
       * angles relative to center, assuming the following:
       *     * eye is aligned with optical center of lens
       *     * display screen is equal or larger than extents viewable through lens
       *     * nominal eye-to-lens distance
       *     * mirrored field of view will be applied to the right eye
       * These values are essentially used as an optimization to avoid rendering
       * pixels which can't be seen.
       * This is a required field for distortion rendering, and angles must be
       * positive.
       * </pre>
       *
       * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
       */
      public Builder addAllLeftEyeFieldOfViewAngles(
          java.lang.Iterable<? extends java.lang.Float> values) {
        copyOnWrite();
        instance.addAllLeftEyeFieldOfViewAngles(values);
        return this;
      }
      /**
       * <pre>
       * Four-element tuple (left, right, bottom, top) of left eye's view extent
       * angles relative to center, assuming the following:
       *     * eye is aligned with optical center of lens
       *     * display screen is equal or larger than extents viewable through lens
       *     * nominal eye-to-lens distance
       *     * mirrored field of view will be applied to the right eye
       * These values are essentially used as an optimization to avoid rendering
       * pixels which can't be seen.
       * This is a required field for distortion rendering, and angles must be
       * positive.
       * </pre>
       *
       * <code>repeated float left_eye_field_of_view_angles = 5 [packed = true];</code>
       */
      public Builder clearLeftEyeFieldOfViewAngles() {
        copyOnWrite();
        instance.clearLeftEyeFieldOfViewAngles();
        return this;
      }

      /**
       * <pre>
       * Set according to vertical alignment strategy-- see enum comments above.
       * NOTE: If you set this to CENTER, see special instructions for the
       * tray_to_lens_distance field below.
       * </pre>
       *
       * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
       */
      public boolean hasVerticalAlignment() {
        return instance.hasVerticalAlignment();
      }
      /**
       * <pre>
       * Set according to vertical alignment strategy-- see enum comments above.
       * NOTE: If you set this to CENTER, see special instructions for the
       * tray_to_lens_distance field below.
       * </pre>
       *
       * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
       */
      public DeviceParams.VerticalAlignmentType getVerticalAlignment() {
        return instance.getVerticalAlignment();
      }
      /**
       * <pre>
       * Set according to vertical alignment strategy-- see enum comments above.
       * NOTE: If you set this to CENTER, see special instructions for the
       * tray_to_lens_distance field below.
       * </pre>
       *
       * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
       */
      public Builder setVerticalAlignment(CardboardDevice.DeviceParams.VerticalAlignmentType value) {
        copyOnWrite();
        instance.setVerticalAlignment(value);
        return this;
      }
      /**
       * <pre>
       * Set according to vertical alignment strategy-- see enum comments above.
       * NOTE: If you set this to CENTER, see special instructions for the
       * tray_to_lens_distance field below.
       * </pre>
       *
       * <code>optional .cardboard.DeviceParams.VerticalAlignmentType vertical_alignment = 11 [default = BOTTOM];</code>
       */
      public Builder clearVerticalAlignment() {
        copyOnWrite();
        instance.clearVerticalAlignment();
        return this;
      }

      /**
       * <pre>
       * If the phone is aligned vertically within the device by resting against
       * a fixed top or bottom tray, this is the distance from the tray to
       * optical center of the lenses.
       * This is a required field for distortion rendering, and must be positive.
       * NOTE: Due to a bug in initial versions of the SDK's, this field
       * must be set explicitly to .035 when vertical_alignment = CENTER.
       * </pre>
       *
       * <code>optional float tray_to_lens_distance = 6;</code>
       */
      public boolean hasTrayToLensDistance() {
        return instance.hasTrayToLensDistance();
      }
      /**
       * <pre>
       * If the phone is aligned vertically within the device by resting against
       * a fixed top or bottom tray, this is the distance from the tray to
       * optical center of the lenses.
       * This is a required field for distortion rendering, and must be positive.
       * NOTE: Due to a bug in initial versions of the SDK's, this field
       * must be set explicitly to .035 when vertical_alignment = CENTER.
       * </pre>
       *
       * <code>optional float tray_to_lens_distance = 6;</code>
       */
      public float getTrayToLensDistance() {
        return instance.getTrayToLensDistance();
      }
      /**
       * <pre>
       * If the phone is aligned vertically within the device by resting against
       * a fixed top or bottom tray, this is the distance from the tray to
       * optical center of the lenses.
       * This is a required field for distortion rendering, and must be positive.
       * NOTE: Due to a bug in initial versions of the SDK's, this field
       * must be set explicitly to .035 when vertical_alignment = CENTER.
       * </pre>
       *
       * <code>optional float tray_to_lens_distance = 6;</code>
       */
      public Builder setTrayToLensDistance(float value) {
        copyOnWrite();
        instance.setTrayToLensDistance(value);
        return this;
      }
      /**
       * <pre>
       * If the phone is aligned vertically within the device by resting against
       * a fixed top or bottom tray, this is the distance from the tray to
       * optical center of the lenses.
       * This is a required field for distortion rendering, and must be positive.
       * NOTE: Due to a bug in initial versions of the SDK's, this field
       * must be set explicitly to .035 when vertical_alignment = CENTER.
       * </pre>
       *
       * <code>optional float tray_to_lens_distance = 6;</code>
       */
      public Builder clearTrayToLensDistance() {
        copyOnWrite();
        instance.clearTrayToLensDistance();
        return this;
      }

      /**
       * <pre>
       * Coefficients Ki for pincushion distortion function which maps
       * from position on real screen to virtual screen (i.e. texture) relative
       * to optical center:
       *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
       * where r is the distance in tan-angle units from the optical center,
       * p the input point, and p' the output point.  Tan-angle units can be
       * computed as distance on the screen divided by distance from the
       * virtual eye to the screen.
       * </pre>
       *
       * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
       */
      public java.util.List<java.lang.Float>
          getDistortionCoefficientsList() {
        return java.util.Collections.unmodifiableList(
            instance.getDistortionCoefficientsList());
      }
      /**
       * <pre>
       * Coefficients Ki for pincushion distortion function which maps
       * from position on real screen to virtual screen (i.e. texture) relative
       * to optical center:
       *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
       * where r is the distance in tan-angle units from the optical center,
       * p the input point, and p' the output point.  Tan-angle units can be
       * computed as distance on the screen divided by distance from the
       * virtual eye to the screen.
       * </pre>
       *
       * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
       */
      public int getDistortionCoefficientsCount() {
        return instance.getDistortionCoefficientsCount();
      }
      /**
       * <pre>
       * Coefficients Ki for pincushion distortion function which maps
       * from position on real screen to virtual screen (i.e. texture) relative
       * to optical center:
       *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
       * where r is the distance in tan-angle units from the optical center,
       * p the input point, and p' the output point.  Tan-angle units can be
       * computed as distance on the screen divided by distance from the
       * virtual eye to the screen.
       * </pre>
       *
       * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
       */
      public float getDistortionCoefficients(int index) {
        return instance.getDistortionCoefficients(index);
      }
      /**
       * <pre>
       * Coefficients Ki for pincushion distortion function which maps
       * from position on real screen to virtual screen (i.e. texture) relative
       * to optical center:
       *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
       * where r is the distance in tan-angle units from the optical center,
       * p the input point, and p' the output point.  Tan-angle units can be
       * computed as distance on the screen divided by distance from the
       * virtual eye to the screen.
       * </pre>
       *
       * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
       */
      public Builder setDistortionCoefficients(
          int index, float value) {
        copyOnWrite();
        instance.setDistortionCoefficients(index, value);
        return this;
      }
      /**
       * <pre>
       * Coefficients Ki for pincushion distortion function which maps
       * from position on real screen to virtual screen (i.e. texture) relative
       * to optical center:
       *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
       * where r is the distance in tan-angle units from the optical center,
       * p the input point, and p' the output point.  Tan-angle units can be
       * computed as distance on the screen divided by distance from the
       * virtual eye to the screen.
       * </pre>
       *
       * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
       */
      public Builder addDistortionCoefficients(float value) {
        copyOnWrite();
        instance.addDistortionCoefficients(value);
        return this;
      }
      /**
       * <pre>
       * Coefficients Ki for pincushion distortion function which maps
       * from position on real screen to virtual screen (i.e. texture) relative
       * to optical center:
       *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
       * where r is the distance in tan-angle units from the optical center,
       * p the input point, and p' the output point.  Tan-angle units can be
       * computed as distance on the screen divided by distance from the
       * virtual eye to the screen.
       * </pre>
       *
       * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
       */
      public Builder addAllDistortionCoefficients(
          java.lang.Iterable<? extends java.lang.Float> values) {
        copyOnWrite();
        instance.addAllDistortionCoefficients(values);
        return this;
      }
      /**
       * <pre>
       * Coefficients Ki for pincushion distortion function which maps
       * from position on real screen to virtual screen (i.e. texture) relative
       * to optical center:
       *    p' = p (1 + K1 r^2 + K2 r^4 + ... + Kn r^(2n))
       * where r is the distance in tan-angle units from the optical center,
       * p the input point, and p' the output point.  Tan-angle units can be
       * computed as distance on the screen divided by distance from the
       * virtual eye to the screen.
       * </pre>
       *
       * <code>repeated float distortion_coefficients = 7 [packed = true];</code>
       */
      public Builder clearDistortionCoefficients() {
        copyOnWrite();
        instance.clearDistortionCoefficients();
        return this;
      }

      /**
       * <pre>
       * Specify primary input mechanism of the HMD.  Intended for advisory
       * purposes only, to address simple questions such as "can HMD
       * be used with apps requiring a physical button event?" or "what icon
       * should be used to represent button action to the user?".
       * </pre>
       *
       * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
       */
      public boolean hasPrimaryButton() {
        return instance.hasPrimaryButton();
      }
      /**
       * <pre>
       * Specify primary input mechanism of the HMD.  Intended for advisory
       * purposes only, to address simple questions such as "can HMD
       * be used with apps requiring a physical button event?" or "what icon
       * should be used to represent button action to the user?".
       * </pre>
       *
       * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
       */
      public DeviceParams.ButtonType getPrimaryButton() {
        return instance.getPrimaryButton();
      }
      /**
       * <pre>
       * Specify primary input mechanism of the HMD.  Intended for advisory
       * purposes only, to address simple questions such as "can HMD
       * be used with apps requiring a physical button event?" or "what icon
       * should be used to represent button action to the user?".
       * </pre>
       *
       * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
       */
      public Builder setPrimaryButton(CardboardDevice.DeviceParams.ButtonType value) {
        copyOnWrite();
        instance.setPrimaryButton(value);
        return this;
      }
      /**
       * <pre>
       * Specify primary input mechanism of the HMD.  Intended for advisory
       * purposes only, to address simple questions such as "can HMD
       * be used with apps requiring a physical button event?" or "what icon
       * should be used to represent button action to the user?".
       * </pre>
       *
       * <code>optional .cardboard.DeviceParams.ButtonType primary_button = 12 [default = MAGNET];</code>
       */
      public Builder clearPrimaryButton() {
        copyOnWrite();
        instance.clearPrimaryButton();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cardboard.DeviceParams)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new CardboardDevice.DeviceParams();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          leftEyeFieldOfViewAngles_.makeImmutable();
          distortionCoefficients_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          CardboardDevice.DeviceParams other = (CardboardDevice.DeviceParams) arg1;
          vendor_ = visitor.visitString(
              hasVendor(), vendor_,
              other.hasVendor(), other.vendor_);
          model_ = visitor.visitString(
              hasModel(), model_,
              other.hasModel(), other.model_);
          screenToLensDistance_ = visitor.visitFloat(
              hasScreenToLensDistance(), screenToLensDistance_,
              other.hasScreenToLensDistance(), other.screenToLensDistance_);
          interLensDistance_ = visitor.visitFloat(
              hasInterLensDistance(), interLensDistance_,
              other.hasInterLensDistance(), other.interLensDistance_);
          leftEyeFieldOfViewAngles_= visitor.visitFloatList(leftEyeFieldOfViewAngles_, other.leftEyeFieldOfViewAngles_);
          verticalAlignment_ = visitor.visitInt(hasVerticalAlignment(), verticalAlignment_,
              other.hasVerticalAlignment(), other.verticalAlignment_);
          trayToLensDistance_ = visitor.visitFloat(
              hasTrayToLensDistance(), trayToLensDistance_,
              other.hasTrayToLensDistance(), other.trayToLensDistance_);
          distortionCoefficients_= visitor.visitFloatList(distortionCoefficients_, other.distortionCoefficients_);
          primaryButton_ = visitor.visitInt(hasPrimaryButton(), primaryButton_,
              other.hasPrimaryButton(), other.primaryButton_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  vendor_ = s;
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  model_ = s;
                  break;
                }
                case 29: {
                  bitField0_ |= 0x00000004;
                  screenToLensDistance_ = input.readFloat();
                  break;
                }
                case 37: {
                  bitField0_ |= 0x00000008;
                  interLensDistance_ = input.readFloat();
                  break;
                }
                case 45: {
                  if (!leftEyeFieldOfViewAngles_.isModifiable()) {
                    leftEyeFieldOfViewAngles_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(leftEyeFieldOfViewAngles_);
                  }
                  leftEyeFieldOfViewAngles_.addFloat(input.readFloat());
                  break;
                }
                case 42: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  if (!leftEyeFieldOfViewAngles_.isModifiable() && input.getBytesUntilLimit() > 0) {
                    final int currentSize = leftEyeFieldOfViewAngles_.size();
                    leftEyeFieldOfViewAngles_ = leftEyeFieldOfViewAngles_.mutableCopyWithCapacity(
                        currentSize + (length/4));
                  }
                  while (input.getBytesUntilLimit() > 0) {
                    leftEyeFieldOfViewAngles_.addFloat(input.readFloat());
                  }
                  input.popLimit(limit);
                  break;
                }
                case 53: {
                  bitField0_ |= 0x00000020;
                  trayToLensDistance_ = input.readFloat();
                  break;
                }
                case 61: {
                  if (!distortionCoefficients_.isModifiable()) {
                    distortionCoefficients_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(distortionCoefficients_);
                  }
                  distortionCoefficients_.addFloat(input.readFloat());
                  break;
                }
                case 58: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  if (!distortionCoefficients_.isModifiable() && input.getBytesUntilLimit() > 0) {
                    final int currentSize = distortionCoefficients_.size();
                    distortionCoefficients_ = distortionCoefficients_.mutableCopyWithCapacity(
                        currentSize + (length/4));
                  }
                  while (input.getBytesUntilLimit() > 0) {
                    distortionCoefficients_.addFloat(input.readFloat());
                  }
                  input.popLimit(limit);
                  break;
                }
                case 88: {
                  int rawValue = input.readEnum();
                  CardboardDevice.DeviceParams.VerticalAlignmentType value = CardboardDevice.DeviceParams.VerticalAlignmentType.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(11, rawValue);
                  } else {
                    bitField0_ |= 0x00000010;
                    verticalAlignment_ = rawValue;
                  }
                  break;
                }
                case 96: {
                  int rawValue = input.readEnum();
                  CardboardDevice.DeviceParams.ButtonType value = CardboardDevice.DeviceParams.ButtonType.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(12, rawValue);
                  } else {
                    bitField0_ |= 0x00000040;
                    primaryButton_ = rawValue;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (CardboardDevice.DeviceParams.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:cardboard.DeviceParams)
    private static final CardboardDevice.DeviceParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DeviceParams();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static CardboardDevice.DeviceParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DeviceParams> PARSER;

    public static com.google.protobuf.Parser<DeviceParams> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
